parameters:
    wmds_mind_body_api.class: Wmds\MindBodyAPIBundle\MindbodyOnlineAPI\MindbodyOnlineAPI

services:
    wmds_mind_body_api:
        class: %wmds_mind_body_api.class%
        arguments: [@service_container]
