parameters:
#    wmds_mind_body_api.example.class: Wmds\MindBodyAPIBundle\Example

services:
#    wmds_mind_body_api.example:
#        class: %wmds_mind_body_api.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
